// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package custody

// Account discriminators
var (
	Account_Config           = [8]byte{155, 12, 170, 224, 30, 250, 204, 130}
	Account_WithdrawalRecord = [8]byte{88, 59, 154, 202, 216, 210, 211, 237}
)

// Event discriminators
var (
	Event_Deposited      = [8]byte{111, 141, 26, 45, 161, 35, 100, 57}
	Event_Executed       = [8]byte{8, 232, 139, 132, 197, 45, 29, 164}
	Event_SignersUpdated = [8]byte{71, 177, 47, 237, 194, 42, 20, 105}
)

// Instruction discriminators
var (
	Instruction_DepositSol    = [8]byte{108, 81, 78, 117, 125, 155, 56, 200}
	Instruction_DepositSpl    = [8]byte{224, 0, 198, 175, 198, 47, 105, 204}
	Instruction_Execute       = [8]byte{130, 221, 242, 154, 13, 193, 189, 29}
	Instruction_Initialize    = [8]byte{175, 175, 109, 31, 13, 152, 155, 237}
	Instruction_UpdateSigners = [8]byte{228, 82, 68, 150, 92, 66, 140, 174}
)
