// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the events defined in the IDL.

package custody

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyEvent(eventData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek event discriminator: %w", err)
	}
	switch discriminator {
	case Event_Deposited:
		value := new(Deposited)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as Deposited: %w", err)
		}
		return value, nil
	case Event_Executed:
		value := new(Executed)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as Executed: %w", err)
		}
		return value, nil
	case Event_SignersUpdated:
		value := new(SignersUpdated)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as SignersUpdated: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseEvent_Deposited(eventData []byte) (*Deposited, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_Deposited {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_Deposited, binary.FormatDiscriminator(discriminator))
	}
	event := new(Deposited)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type Deposited: %w", err)
	}
	return event, nil
}

func ParseEvent_Executed(eventData []byte) (*Executed, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_Executed {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_Executed, binary.FormatDiscriminator(discriminator))
	}
	event := new(Executed)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type Executed: %w", err)
	}
	return event, nil
}

func ParseEvent_SignersUpdated(eventData []byte) (*SignersUpdated, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_SignersUpdated {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_SignersUpdated, binary.FormatDiscriminator(discriminator))
	}
	event := new(SignersUpdated)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type SignersUpdated: %w", err)
	}
	return event, nil
}
