// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package custody

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "deposit_sol" instruction.
// Native SOL deposit crediting the 20-byte clearnet `account`, with an // optional ADR-015 sub-account `reference` ([0u8; 32] for none).
func NewDepositSolInstruction(
	// Params:
	accountParam [20]uint8,
	referenceParam [32]uint8,
	amountParam uint64,

	// Accounts:
	depositorAccount solanago.PublicKey,
	vaultAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_DepositSol[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `accountParam`:
		err = enc__.Encode(accountParam)
		if err != nil {
			return nil, errors.NewField("accountParam", err)
		}
		// Serialize `referenceParam`:
		err = enc__.Encode(referenceParam)
		if err != nil {
			return nil, errors.NewField("referenceParam", err)
		}
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "depositor": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(depositorAccount, true, true))
		// Account 1 "vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(vaultAccount, true, false))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 3 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 4 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "deposit_spl" instruction.
// SPL token deposit crediting the 20-byte clearnet `account`, with an // optional ADR-015 sub-account `reference` ([0u8; 32] for none).
func NewDepositSplInstruction(
	// Params:
	accountParam [20]uint8,
	referenceParam [32]uint8,
	amountParam uint64,

	// Accounts:
	depositorAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	depositorAtaAccount solanago.PublicKey,
	vaultAccount solanago.PublicKey,
	vaultAtaAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_DepositSpl[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `accountParam`:
		err = enc__.Encode(accountParam)
		if err != nil {
			return nil, errors.NewField("accountParam", err)
		}
		// Serialize `referenceParam`:
		err = enc__.Encode(referenceParam)
		if err != nil {
			return nil, errors.NewField("referenceParam", err)
		}
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "depositor": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(depositorAccount, true, true))
		// Account 1 "mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintAccount, false, false))
		// Account 2 "depositor_ata": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(depositorAtaAccount, true, false))
		// Account 3 "vault": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(vaultAccount, false, false))
		// Account 4 "vault_ata": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(vaultAtaAccount, true, false))
		// Account 5 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 6 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 7 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 8 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "execute" instruction.
// Execute a quorum-authorized withdrawal (native or SPL).
func NewExecuteInstruction(
	// Params:
	toParam solanago.PublicKey,
	mintParam solanago.PublicKey,
	amountParam uint64,
	withdrawalIdParam [32]uint8,
	sigIxIndexParam uint8,

	// Accounts:
	feePayerAccount solanago.PublicKey,
	configAccount solanago.PublicKey,
	vaultAccount solanago.PublicKey,
	withdrawalAccount solanago.PublicKey,
	recipientAccount solanago.PublicKey,
	instructionsAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Execute[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `toParam`:
		err = enc__.Encode(toParam)
		if err != nil {
			return nil, errors.NewField("toParam", err)
		}
		// Serialize `mintParam`:
		err = enc__.Encode(mintParam)
		if err != nil {
			return nil, errors.NewField("mintParam", err)
		}
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
		// Serialize `withdrawalIdParam`:
		err = enc__.Encode(withdrawalIdParam)
		if err != nil {
			return nil, errors.NewField("withdrawalIdParam", err)
		}
		// Serialize `sigIxIndexParam`:
		err = enc__.Encode(sigIxIndexParam)
		if err != nil {
			return nil, errors.NewField("sigIxIndexParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "fee_payer": Writable, Signer, Required
		// Pays the WithdrawalRecord rent and the transaction fee. Authorizes no
		// custody action — distinct from the provider custody signers.
		accounts__.Append(solanago.NewAccountMeta(feePayerAccount, true, true))
		// Account 1 "config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(configAccount, false, false))
		// Account 2 "vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(vaultAccount, true, false))
		// Account 3 "withdrawal": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(withdrawalAccount, true, false))
		// Account 4 "recipient": Writable, Non-signer, Required
		// for SPL it is only used to derive the recipient ATA. Pinned to `to`.
		accounts__.Append(solanago.NewAccountMeta(recipientAccount, true, false))
		// Account 5 "instructions": Read-only, Non-signer, Required, Address: Sysvar1nstructions1111111111111111111111111
		// address constraint plus `load_instruction_at_checked` both verify it.
		accounts__.Append(solanago.NewAccountMeta(instructionsAccount, false, false))
		// Account 6 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 7 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 8 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "initialize" instruction.
// One-time setup of the Config PDA (signer set, threshold, chain_id).
func NewInitializeInstruction(
	// Params:
	signersParam []solanago.PublicKey,
	thresholdParam uint8,
	chainIdParam uint64,

	// Accounts:
	configAccount solanago.PublicKey,
	payerAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
	programDataAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Initialize[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `signersParam`:
		err = enc__.Encode(signersParam)
		if err != nil {
			return nil, errors.NewField("signersParam", err)
		}
		// Serialize `thresholdParam`:
		err = enc__.Encode(thresholdParam)
		if err != nil {
			return nil, errors.NewField("thresholdParam", err)
		}
		// Serialize `chainIdParam`:
		err = enc__.Encode(chainIdParam)
		if err != nil {
			return nil, errors.NewField("chainIdParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "config": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(configAccount, true, false))
		// Account 1 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 2 "program": Read-only, Non-signer, Required, Address: 98eVpih8X9CAcgU9bzNB9V7VtkRrnFZUmqzEnsq7cfmg
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
		// Account 3 "program_data": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programDataAccount, false, false))
		// Account 4 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "update_signers" instruction.
// In-place signer rotation (ADR-013 Flow A).
func NewUpdateSignersInstruction(
	// Params:
	newSignersParam []solanago.PublicKey,
	newThresholdParam uint8,
	sigIxIndexParam uint8,

	// Accounts:
	configAccount solanago.PublicKey,
	instructionsAccount solanago.PublicKey,
	eventAuthorityAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_UpdateSigners[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newSignersParam`:
		err = enc__.Encode(newSignersParam)
		if err != nil {
			return nil, errors.NewField("newSignersParam", err)
		}
		// Serialize `newThresholdParam`:
		err = enc__.Encode(newThresholdParam)
		if err != nil {
			return nil, errors.NewField("newThresholdParam", err)
		}
		// Serialize `sigIxIndexParam`:
		err = enc__.Encode(sigIxIndexParam)
		if err != nil {
			return nil, errors.NewField("sigIxIndexParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "config": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(configAccount, true, false))
		// Account 1 "instructions": Read-only, Non-signer, Required, Address: Sysvar1nstructions1111111111111111111111111
		accounts__.Append(solanago.NewAccountMeta(instructionsAccount, false, false))
		// Account 2 "event_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(eventAuthorityAccount, false, false))
		// Account 3 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}
