// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package custody

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Config PDA — seeds `["config"]`. The on-chain analogue of `Custody.sol`'s
// signer set + threshold + nonce. `signers` is kept strictly ascending so a
// linear membership scan in the Ed25519 verifier is unambiguous.
type Config struct {
	Signers     []solanago.PublicKey `json:"signers"`
	Threshold   uint8                `json:"threshold"`
	SignerNonce uint64               `json:"signerNonce"`
	ChainId     uint64               `json:"chainId"`
	Bump        uint8                `json:"bump"`
}

func (obj Config) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Signers`:
	err = encoder.Encode(obj.Signers)
	if err != nil {
		return errors.NewField("Signers", err)
	}
	// Serialize `Threshold`:
	err = encoder.Encode(obj.Threshold)
	if err != nil {
		return errors.NewField("Threshold", err)
	}
	// Serialize `SignerNonce`:
	err = encoder.Encode(obj.SignerNonce)
	if err != nil {
		return errors.NewField("SignerNonce", err)
	}
	// Serialize `ChainId`:
	err = encoder.Encode(obj.ChainId)
	if err != nil {
		return errors.NewField("ChainId", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj Config) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Config: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Config) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Signers`:
	err = decoder.Decode(&obj.Signers)
	if err != nil {
		return errors.NewField("Signers", err)
	}
	// Deserialize `Threshold`:
	err = decoder.Decode(&obj.Threshold)
	if err != nil {
		return errors.NewField("Threshold", err)
	}
	// Deserialize `SignerNonce`:
	err = decoder.Decode(&obj.SignerNonce)
	if err != nil {
		return errors.NewField("SignerNonce", err)
	}
	// Deserialize `ChainId`:
	err = decoder.Decode(&obj.ChainId)
	if err != nil {
		return errors.NewField("ChainId", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *Config) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Config: %w", err)
	}
	return nil
}

func UnmarshalConfig(buf []byte) (*Config, error) {
	obj := new(Config)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted by `deposit_sol` / `deposit_spl` via `emit_cpi!`. The custody
// watcher decodes these from the self-CPI inner instructions and turns each
// into a `chains.DepositEvent`. `mint == Pubkey::default()` denotes native
// SOL (the analogue of EVM's `asset == address(0)`). `account` is the 20-byte
// clearnet account the deposit credits.
type Deposited struct {
	Depositor solanago.PublicKey `json:"depositor"`
	Account   [20]uint8          `json:"account"`
	Mint      solanago.PublicKey `json:"mint"`
	Amount    uint64             `json:"amount"`
}

func (obj Deposited) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Depositor`:
	err = encoder.Encode(obj.Depositor)
	if err != nil {
		return errors.NewField("Depositor", err)
	}
	// Serialize `Account`:
	err = encoder.Encode(obj.Account)
	if err != nil {
		return errors.NewField("Account", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `Amount`:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	return nil
}

func (obj Deposited) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Deposited: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Deposited) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Depositor`:
	err = decoder.Decode(&obj.Depositor)
	if err != nil {
		return errors.NewField("Depositor", err)
	}
	// Deserialize `Account`:
	err = decoder.Decode(&obj.Account)
	if err != nil {
		return errors.NewField("Account", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	return nil
}

func (obj *Deposited) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Deposited: %w", err)
	}
	return nil
}

func UnmarshalDeposited(buf []byte) (*Deposited, error) {
	obj := new(Deposited)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted by `execute` via `emit_cpi!`. The watcher writes a ledger row keyed
// by `withdrawal_id` (the reconciliation key against `signing_wal`).
type Executed struct {
	WithdrawalId [32]uint8          `json:"withdrawalId"`
	To           solanago.PublicKey `json:"to"`
	Mint         solanago.PublicKey `json:"mint"`
	Amount       uint64             `json:"amount"`
}

func (obj Executed) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `WithdrawalId`:
	err = encoder.Encode(obj.WithdrawalId)
	if err != nil {
		return errors.NewField("WithdrawalId", err)
	}
	// Serialize `To`:
	err = encoder.Encode(obj.To)
	if err != nil {
		return errors.NewField("To", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `Amount`:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	return nil
}

func (obj Executed) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Executed: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Executed) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `WithdrawalId`:
	err = decoder.Decode(&obj.WithdrawalId)
	if err != nil {
		return errors.NewField("WithdrawalId", err)
	}
	// Deserialize `To`:
	err = decoder.Decode(&obj.To)
	if err != nil {
		return errors.NewField("To", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	return nil
}

func (obj *Executed) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Executed: %w", err)
	}
	return nil
}

func UnmarshalExecuted(buf []byte) (*Executed, error) {
	obj := new(Executed)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted by `update_signers` via `emit_cpi!`.
type SignersUpdated struct {
	Signers     []solanago.PublicKey `json:"signers"`
	Threshold   uint8                `json:"threshold"`
	SignerNonce uint64               `json:"signerNonce"`
}

func (obj SignersUpdated) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Signers`:
	err = encoder.Encode(obj.Signers)
	if err != nil {
		return errors.NewField("Signers", err)
	}
	// Serialize `Threshold`:
	err = encoder.Encode(obj.Threshold)
	if err != nil {
		return errors.NewField("Threshold", err)
	}
	// Serialize `SignerNonce`:
	err = encoder.Encode(obj.SignerNonce)
	if err != nil {
		return errors.NewField("SignerNonce", err)
	}
	return nil
}

func (obj SignersUpdated) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SignersUpdated: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SignersUpdated) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Signers`:
	err = decoder.Decode(&obj.Signers)
	if err != nil {
		return errors.NewField("Signers", err)
	}
	// Deserialize `Threshold`:
	err = decoder.Decode(&obj.Threshold)
	if err != nil {
		return errors.NewField("Threshold", err)
	}
	// Deserialize `SignerNonce`:
	err = decoder.Decode(&obj.SignerNonce)
	if err != nil {
		return errors.NewField("SignerNonce", err)
	}
	return nil
}

func (obj *SignersUpdated) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SignersUpdated: %w", err)
	}
	return nil
}

func UnmarshalSignersUpdated(buf []byte) (*SignersUpdated, error) {
	obj := new(SignersUpdated)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// WithdrawalRecord PDA — seeds `["withdrawal", withdrawal_id]`. Its mere
// existence is the replay guard: `execute` creates it with `init`, so a
// second execution of the same `withdrawal_id` fails at account creation.
// The analogue of `Custody.sol`'s `executed[withdrawalId]` storage slot;
// never closed (closing would re-enable replay).
type WithdrawalRecord struct {
	To     solanago.PublicKey `json:"to"`
	Mint   solanago.PublicKey `json:"mint"`
	Amount uint64             `json:"amount"`
}

func (obj WithdrawalRecord) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `To`:
	err = encoder.Encode(obj.To)
	if err != nil {
		return errors.NewField("To", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `Amount`:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	return nil
}

func (obj WithdrawalRecord) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding WithdrawalRecord: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *WithdrawalRecord) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `To`:
	err = decoder.Decode(&obj.To)
	if err != nil {
		return errors.NewField("To", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	return nil
}

func (obj *WithdrawalRecord) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling WithdrawalRecord: %w", err)
	}
	return nil
}

func UnmarshalWithdrawalRecord(buf []byte) (*WithdrawalRecord, error) {
	obj := new(WithdrawalRecord)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
