export const BITCOIN_NATIVE_ASSET = "BTC";

export const BITCOIN_DUST_THRESHOLD_SATS = 330n;
export const BITCOIN_DEFAULT_MIN_FUNDING_CONFIRMATIONS = 1n;
export const BITCOIN_DEFAULT_FEE_TARGET_BLOCKS = 6n;
export const BITCOIN_DEFAULT_FALLBACK_FEE_RATE_SAT_PER_VBYTE = 5n;
export const BITCOIN_MAX_SIGNED_SATS = (1n << 63n) - 1n;
export const BITCOIN_MAX_VAULT_PUBKEYS = 15;
