// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package core

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
	big "math/big"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

var lengthBufBlockHeader = []byte{134}

func (t *BlockHeader) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufBlockHeader); err != nil {
		return err
	}

	// t.Anchor ([32]uint8) (array)
	if len(t.Anchor) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Anchor was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Anchor))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Anchor[:]); err != nil {
		return err
	}

	// t.SealedAt (int64) (int64)
	if t.SealedAt >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.SealedAt)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.SealedAt-1)); err != nil {
			return err
		}
	}

	// t.StateRoot ([32]uint8) (array)
	if len(t.StateRoot) > 2097152 {
		return xerrors.Errorf("Byte array in field t.StateRoot was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.StateRoot))); err != nil {
		return err
	}

	if _, err := cw.Write(t.StateRoot[:]); err != nil {
		return err
	}

	// t.EntriesDigest ([32]uint8) (array)
	if len(t.EntriesDigest) > 2097152 {
		return xerrors.Errorf("Byte array in field t.EntriesDigest was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.EntriesDigest))); err != nil {
		return err
	}

	if _, err := cw.Write(t.EntriesDigest[:]); err != nil {
		return err
	}

	// t.K (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.K)); err != nil {
		return err
	}

	// t.Accounts ([]core.AccountSnapshot) (slice)
	if len(t.Accounts) > 8192 {
		return xerrors.Errorf("Slice value in field t.Accounts was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Accounts))); err != nil {
		return err
	}
	for _, v := range t.Accounts {
		if err := v.MarshalCBOR(cw); err != nil {
			return err
		}

	}
	return nil
}

func (t *BlockHeader) UnmarshalCBOR(r io.Reader) (err error) {
	*t = BlockHeader{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 6 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Anchor ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.Anchor: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.Anchor = [32]uint8{}
	if _, err := io.ReadFull(cr, t.Anchor[:]); err != nil {
		return err
	}
	// t.SealedAt (int64) (int64)
	{
		maj, extra, err := cr.ReadHeader()
		if err != nil {
			return err
		}
		var extraI int64
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative overflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.SealedAt = int64(extraI)
	}
	// t.StateRoot ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.StateRoot: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.StateRoot = [32]uint8{}
	if _, err := io.ReadFull(cr, t.StateRoot[:]); err != nil {
		return err
	}
	// t.EntriesDigest ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.EntriesDigest: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.EntriesDigest = [32]uint8{}
	if _, err := io.ReadFull(cr, t.EntriesDigest[:]); err != nil {
		return err
	}
	// t.K (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.K = uint64(extra)

	}
	// t.Accounts ([]core.AccountSnapshot) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 8192 {
		return fmt.Errorf("t.Accounts: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Accounts = make([]AccountSnapshot, extra)
	}

	for i := 0; i < int(extra); i++ {
		{
			var maj byte
			var extra uint64
			var err error
			_ = maj
			_ = extra
			_ = err

			{

				if err := t.Accounts[i].UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Accounts[i]: %w", err)
				}

			}

		}
	}
	return nil
}

var lengthBufBlock = []byte{139}

func (t *Block) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufBlock); err != nil {
		return err
	}

	// t.Anchor ([32]uint8) (array)
	if len(t.Anchor) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Anchor was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Anchor))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Anchor[:]); err != nil {
		return err
	}

	// t.SealedAt (int64) (int64)
	if t.SealedAt >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.SealedAt)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.SealedAt-1)); err != nil {
			return err
		}
	}

	// t.Entries ([]core.BlockEntry) (slice)
	if len(t.Entries) > 8192 {
		return xerrors.Errorf("Slice value in field t.Entries was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Entries))); err != nil {
		return err
	}
	for _, v := range t.Entries {
		if err := v.MarshalCBOR(cw); err != nil {
			return err
		}

	}

	// t.StateRoot ([32]uint8) (array)
	if len(t.StateRoot) > 2097152 {
		return xerrors.Errorf("Byte array in field t.StateRoot was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.StateRoot))); err != nil {
		return err
	}

	if _, err := cw.Write(t.StateRoot[:]); err != nil {
		return err
	}

	// t.EntriesDigest ([32]uint8) (array)
	if len(t.EntriesDigest) > 2097152 {
		return xerrors.Errorf("Byte array in field t.EntriesDigest was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.EntriesDigest))); err != nil {
		return err
	}

	if _, err := cw.Write(t.EntriesDigest[:]); err != nil {
		return err
	}

	// t.K (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.K)); err != nil {
		return err
	}

	// t.Attestation (core.Attestation) (struct)
	if err := t.Attestation.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Accounts ([]core.AccountSnapshot) (slice)
	if len(t.Accounts) > 8192 {
		return xerrors.Errorf("Slice value in field t.Accounts was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Accounts))); err != nil {
		return err
	}
	for _, v := range t.Accounts {
		if err := v.MarshalCBOR(cw); err != nil {
			return err
		}

	}

	// t.EventBloom ([256]uint8) (array)
	if len(t.EventBloom) > 2097152 {
		return xerrors.Errorf("Byte array in field t.EventBloom was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.EventBloom))); err != nil {
		return err
	}

	if _, err := cw.Write(t.EventBloom[:]); err != nil {
		return err
	}

	// t.AggregateVaR (big.Int) (struct)
	{
		if t.AggregateVaR != nil && t.AggregateVaR.Sign() < 0 {
			return xerrors.Errorf("Value in field t.AggregateVaR was a negative big-integer (not supported)")
		}
		if err := cw.CborWriteHeader(cbg.MajTag, 2); err != nil {
			return err
		}
		var b []byte
		if t.AggregateVaR != nil {
			b = t.AggregateVaR.Bytes()
		}

		if err := cw.CborWriteHeader(cbg.MajByteString, uint64(len(b))); err != nil {
			return err
		}
		if _, err := cw.Write(b); err != nil {
			return err
		}
	}

	// t.SealReason (string) (string)
	if len(t.SealReason) > 8192 {
		return xerrors.Errorf("Value in field t.SealReason was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.SealReason))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.SealReason)); err != nil {
		return err
	}
	return nil
}

func (t *Block) UnmarshalCBOR(r io.Reader) (err error) {
	*t = Block{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 11 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Anchor ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.Anchor: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.Anchor = [32]uint8{}
	if _, err := io.ReadFull(cr, t.Anchor[:]); err != nil {
		return err
	}
	// t.SealedAt (int64) (int64)
	{
		maj, extra, err := cr.ReadHeader()
		if err != nil {
			return err
		}
		var extraI int64
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative overflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.SealedAt = int64(extraI)
	}
	// t.Entries ([]core.BlockEntry) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 8192 {
		return fmt.Errorf("t.Entries: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Entries = make([]BlockEntry, extra)
	}

	for i := 0; i < int(extra); i++ {
		{
			var maj byte
			var extra uint64
			var err error
			_ = maj
			_ = extra
			_ = err

			{

				if err := t.Entries[i].UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Entries[i]: %w", err)
				}

			}

		}
	}
	// t.StateRoot ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.StateRoot: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.StateRoot = [32]uint8{}
	if _, err := io.ReadFull(cr, t.StateRoot[:]); err != nil {
		return err
	}
	// t.EntriesDigest ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.EntriesDigest: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.EntriesDigest = [32]uint8{}
	if _, err := io.ReadFull(cr, t.EntriesDigest[:]); err != nil {
		return err
	}
	// t.K (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.K = uint64(extra)

	}
	// t.Attestation (core.Attestation) (struct)

	{

		if err := t.Attestation.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.Attestation: %w", err)
		}

	}
	// t.Accounts ([]core.AccountSnapshot) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 8192 {
		return fmt.Errorf("t.Accounts: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Accounts = make([]AccountSnapshot, extra)
	}

	for i := 0; i < int(extra); i++ {
		{
			var maj byte
			var extra uint64
			var err error
			_ = maj
			_ = extra
			_ = err

			{

				if err := t.Accounts[i].UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Accounts[i]: %w", err)
				}

			}

		}
	}
	// t.EventBloom ([256]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.EventBloom: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 256 {
		return fmt.Errorf("expected array to have 256 elements")
	}

	t.EventBloom = [256]uint8{}
	if _, err := io.ReadFull(cr, t.EventBloom[:]); err != nil {
		return err
	}
	// t.AggregateVaR (big.Int) (struct)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if maj != cbg.MajTag || extra != 2 {
		return fmt.Errorf("big ints should be cbor bignums")
	}

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if maj != cbg.MajByteString {
		return fmt.Errorf("big ints should be tagged cbor byte strings")
	}

	if extra > 256 {
		return fmt.Errorf("t.AggregateVaR: cbor bignum was too large")
	}

	if extra > 0 {
		buf := make([]byte, extra)
		if _, err := io.ReadFull(cr, buf); err != nil {
			return err
		}
		t.AggregateVaR = big.NewInt(0).SetBytes(buf)
	} else {
		t.AggregateVaR = big.NewInt(0)
	}
	// t.SealReason (string) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.SealReason = string(sval)
	}
	return nil
}

var lengthBufBlockEntry = []byte{132}

func (t *BlockEntry) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufBlockEntry); err != nil {
		return err
	}

	// t.Type (core.EntryType) (uint8)
	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Type)); err != nil {
		return err
	}

	// t.Account (string) (string)
	if len(t.Account) > 8192 {
		return xerrors.Errorf("Value in field t.Account was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Account))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Account)); err != nil {
		return err
	}

	// t.Nonce (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Nonce)); err != nil {
		return err
	}

	// t.Payload ([]uint8) (slice)
	if len(t.Payload) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Payload was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Payload))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Payload); err != nil {
		return err
	}

	return nil
}

func (t *BlockEntry) UnmarshalCBOR(r io.Reader) (err error) {
	*t = BlockEntry{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 4 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Type (core.EntryType) (uint8)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}
	if maj != cbg.MajUnsignedInt {
		return fmt.Errorf("wrong type for uint8 field")
	}
	if extra > math.MaxUint8 {
		return fmt.Errorf("integer in input was too large for uint8 field")
	}
	t.Type = EntryType(extra)
	// t.Account (string) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.Account = string(sval)
	}
	// t.Nonce (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Nonce = uint64(extra)

	}
	// t.Payload ([]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.Payload: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.Payload = make([]uint8, extra)
	}

	if _, err := io.ReadFull(cr, t.Payload); err != nil {
		return err
	}

	return nil
}

var lengthBufAccountSnapshot = []byte{131}

func (t *AccountSnapshot) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufAccountSnapshot); err != nil {
		return err
	}

	// t.AccountID ([32]uint8) (array)
	if len(t.AccountID) > 2097152 {
		return xerrors.Errorf("Byte array in field t.AccountID was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.AccountID))); err != nil {
		return err
	}

	if _, err := cw.Write(t.AccountID[:]); err != nil {
		return err
	}

	// t.PrevBlockRef ([32]uint8) (array)
	if len(t.PrevBlockRef) > 2097152 {
		return xerrors.Errorf("Byte array in field t.PrevBlockRef was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.PrevBlockRef))); err != nil {
		return err
	}

	if _, err := cw.Write(t.PrevBlockRef[:]); err != nil {
		return err
	}

	// t.PostNonce (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.PostNonce)); err != nil {
		return err
	}

	return nil
}

func (t *AccountSnapshot) UnmarshalCBOR(r io.Reader) (err error) {
	*t = AccountSnapshot{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 3 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.AccountID ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.AccountID: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.AccountID = [32]uint8{}
	if _, err := io.ReadFull(cr, t.AccountID[:]); err != nil {
		return err
	}
	// t.PrevBlockRef ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.PrevBlockRef: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.PrevBlockRef = [32]uint8{}
	if _, err := io.ReadFull(cr, t.PrevBlockRef[:]); err != nil {
		return err
	}
	// t.PostNonce (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.PostNonce = uint64(extra)

	}
	return nil
}

var lengthBufAttestation = []byte{131}

func (t *Attestation) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufAttestation); err != nil {
		return err
	}

	// t.ThresholdSig ([]uint8) (slice)
	if len(t.ThresholdSig) > 2097152 {
		return xerrors.Errorf("Byte array in field t.ThresholdSig was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.ThresholdSig))); err != nil {
		return err
	}

	if _, err := cw.Write(t.ThresholdSig); err != nil {
		return err
	}

	// t.Bitmask ([32]uint8) (array)
	if len(t.Bitmask) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Bitmask was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Bitmask))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Bitmask[:]); err != nil {
		return err
	}

	// t.Validators ([][]uint8) (slice)
	if len(t.Validators) > 8192 {
		return xerrors.Errorf("Slice value in field t.Validators was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Validators))); err != nil {
		return err
	}
	for _, v := range t.Validators {
		if len(v) > 2097152 {
			return xerrors.Errorf("Byte array in field v was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(v))); err != nil {
			return err
		}

		if _, err := cw.Write(v); err != nil {
			return err
		}

	}
	return nil
}

func (t *Attestation) UnmarshalCBOR(r io.Reader) (err error) {
	*t = Attestation{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 3 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.ThresholdSig ([]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.ThresholdSig: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.ThresholdSig = make([]uint8, extra)
	}

	if _, err := io.ReadFull(cr, t.ThresholdSig); err != nil {
		return err
	}

	// t.Bitmask ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.Bitmask: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.Bitmask = [32]uint8{}
	if _, err := io.ReadFull(cr, t.Bitmask[:]); err != nil {
		return err
	}
	// t.Validators ([][]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 8192 {
		return fmt.Errorf("t.Validators: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Validators = make([][]uint8, extra)
	}

	for i := 0; i < int(extra); i++ {
		{
			var maj byte
			var extra uint64
			var err error
			_ = maj
			_ = extra
			_ = err

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.Validators[i]: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.Validators[i] = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.Validators[i]); err != nil {
				return err
			}

		}
	}
	return nil
}

var lengthBufAssetTransfer = []byte{130}

func (t *AssetTransfer) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufAssetTransfer); err != nil {
		return err
	}

	// t.Asset (core.AssetID) (string)
	if len(t.Asset) > 8192 {
		return xerrors.Errorf("Value in field t.Asset was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Asset))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Asset)); err != nil {
		return err
	}

	// t.Amount (decimal.Decimal) (struct)
	if err := t.Amount.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *AssetTransfer) UnmarshalCBOR(r io.Reader) (err error) {
	*t = AssetTransfer{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Asset (core.AssetID) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.Asset = AssetID(sval)
	}
	// t.Amount (decimal.Decimal) (struct)

	{

		if err := t.Amount.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.Amount: %w", err)
		}

	}
	return nil
}

var lengthBufTransferOp = []byte{131}

func (t *TransferOp) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufTransferOp); err != nil {
		return err
	}

	// t.TxID (string) (string)
	if len(t.TxID) > 8192 {
		return xerrors.Errorf("Value in field t.TxID was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.TxID))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.TxID)); err != nil {
		return err
	}

	// t.To (string) (string)
	if len(t.To) > 8192 {
		return xerrors.Errorf("Value in field t.To was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.To))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.To)); err != nil {
		return err
	}

	// t.Assets ([]core.AssetTransfer) (slice)
	if len(t.Assets) > 8192 {
		return xerrors.Errorf("Slice value in field t.Assets was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Assets))); err != nil {
		return err
	}
	for _, v := range t.Assets {
		if err := v.MarshalCBOR(cw); err != nil {
			return err
		}

	}
	return nil
}

func (t *TransferOp) UnmarshalCBOR(r io.Reader) (err error) {
	*t = TransferOp{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 3 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.TxID (string) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.TxID = string(sval)
	}
	// t.To (string) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.To = string(sval)
	}
	// t.Assets ([]core.AssetTransfer) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 8192 {
		return fmt.Errorf("t.Assets: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Assets = make([]AssetTransfer, extra)
	}

	for i := 0; i < int(extra); i++ {
		{
			var maj byte
			var extra uint64
			var err error
			_ = maj
			_ = extra
			_ = err

			{

				if err := t.Assets[i].UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Assets[i]: %w", err)
				}

			}

		}
	}
	return nil
}

var lengthBufSwapOp = []byte{138}

func (t *SwapOp) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufSwapOp); err != nil {
		return err
	}

	// t.TxID (string) (string)
	if len(t.TxID) > 8192 {
		return xerrors.Errorf("Value in field t.TxID was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.TxID))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.TxID)); err != nil {
		return err
	}

	// t.AssetIn (core.AssetID) (string)
	if len(t.AssetIn) > 8192 {
		return xerrors.Errorf("Value in field t.AssetIn was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.AssetIn))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.AssetIn)); err != nil {
		return err
	}

	// t.AssetOut (core.AssetID) (string)
	if len(t.AssetOut) > 8192 {
		return xerrors.Errorf("Value in field t.AssetOut was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.AssetOut))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.AssetOut)); err != nil {
		return err
	}

	// t.AmountIn (decimal.Decimal) (struct)
	if err := t.AmountIn.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.AmountOut (decimal.Decimal) (struct)
	if err := t.AmountOut.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.PoolID (string) (string)
	if len(t.PoolID) > 8192 {
		return xerrors.Errorf("Value in field t.PoolID was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.PoolID))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.PoolID)); err != nil {
		return err
	}

	// t.Fee (decimal.Decimal) (struct)
	if err := t.Fee.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.FeeRate (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.FeeRate)); err != nil {
		return err
	}

	// t.PriceEMA (decimal.Decimal) (struct)
	if err := t.PriceEMA.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.SpotPrice (decimal.Decimal) (struct)
	if err := t.SpotPrice.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *SwapOp) UnmarshalCBOR(r io.Reader) (err error) {
	*t = SwapOp{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 10 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.TxID (string) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.TxID = string(sval)
	}
	// t.AssetIn (core.AssetID) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.AssetIn = AssetID(sval)
	}
	// t.AssetOut (core.AssetID) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.AssetOut = AssetID(sval)
	}
	// t.AmountIn (decimal.Decimal) (struct)

	{

		if err := t.AmountIn.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.AmountIn: %w", err)
		}

	}
	// t.AmountOut (decimal.Decimal) (struct)

	{

		if err := t.AmountOut.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.AmountOut: %w", err)
		}

	}
	// t.PoolID (string) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.PoolID = string(sval)
	}
	// t.Fee (decimal.Decimal) (struct)

	{

		if err := t.Fee.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.Fee: %w", err)
		}

	}
	// t.FeeRate (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.FeeRate = uint64(extra)

	}
	// t.PriceEMA (decimal.Decimal) (struct)

	{

		if err := t.PriceEMA.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.PriceEMA: %w", err)
		}

	}
	// t.SpotPrice (decimal.Decimal) (struct)

	{

		if err := t.SpotPrice.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.SpotPrice: %w", err)
		}

	}
	return nil
}

var lengthBufWithdrawalOp = []byte{134}

func (t *WithdrawalOp) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufWithdrawalOp); err != nil {
		return err
	}

	// t.Asset (core.AssetID) (string)
	if len(t.Asset) > 8192 {
		return xerrors.Errorf("Value in field t.Asset was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Asset))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Asset)); err != nil {
		return err
	}

	// t.L1Asset (string) (string)
	if len(t.L1Asset) > 8192 {
		return xerrors.Errorf("Value in field t.L1Asset was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.L1Asset))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.L1Asset)); err != nil {
		return err
	}

	// t.Amount (decimal.Decimal) (struct)
	if err := t.Amount.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.ChainID (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.ChainID)); err != nil {
		return err
	}

	// t.Recipient (string) (string)
	if len(t.Recipient) > 8192 {
		return xerrors.Errorf("Value in field t.Recipient was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Recipient))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Recipient)); err != nil {
		return err
	}

	// t.UserSignature ([]uint8) (slice)
	if len(t.UserSignature) > 2097152 {
		return xerrors.Errorf("Byte array in field t.UserSignature was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.UserSignature))); err != nil {
		return err
	}

	if _, err := cw.Write(t.UserSignature); err != nil {
		return err
	}

	return nil
}

func (t *WithdrawalOp) UnmarshalCBOR(r io.Reader) (err error) {
	*t = WithdrawalOp{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 6 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Asset (core.AssetID) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.Asset = AssetID(sval)
	}
	// t.L1Asset (string) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.L1Asset = string(sval)
	}
	// t.Amount (decimal.Decimal) (struct)

	{

		if err := t.Amount.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.Amount: %w", err)
		}

	}
	// t.ChainID (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.ChainID = uint64(extra)

	}
	// t.Recipient (string) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.Recipient = string(sval)
	}
	// t.UserSignature ([]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.UserSignature: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.UserSignature = make([]uint8, extra)
	}

	if _, err := io.ReadFull(cr, t.UserSignature); err != nil {
		return err
	}

	return nil
}

var lengthBufRepegOp = []byte{135}

func (t *RepegOp) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufRepegOp); err != nil {
		return err
	}

	// t.PoolID (string) (string)
	if len(t.PoolID) > 8192 {
		return xerrors.Errorf("Value in field t.PoolID was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.PoolID))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.PoolID)); err != nil {
		return err
	}

	// t.OldPriceScale (big.Int) (struct)
	{
		if t.OldPriceScale != nil && t.OldPriceScale.Sign() < 0 {
			return xerrors.Errorf("Value in field t.OldPriceScale was a negative big-integer (not supported)")
		}
		if err := cw.CborWriteHeader(cbg.MajTag, 2); err != nil {
			return err
		}
		var b []byte
		if t.OldPriceScale != nil {
			b = t.OldPriceScale.Bytes()
		}

		if err := cw.CborWriteHeader(cbg.MajByteString, uint64(len(b))); err != nil {
			return err
		}
		if _, err := cw.Write(b); err != nil {
			return err
		}
	}

	// t.NewPriceScale (big.Int) (struct)
	{
		if t.NewPriceScale != nil && t.NewPriceScale.Sign() < 0 {
			return xerrors.Errorf("Value in field t.NewPriceScale was a negative big-integer (not supported)")
		}
		if err := cw.CborWriteHeader(cbg.MajTag, 2); err != nil {
			return err
		}
		var b []byte
		if t.NewPriceScale != nil {
			b = t.NewPriceScale.Bytes()
		}

		if err := cw.CborWriteHeader(cbg.MajByteString, uint64(len(b))); err != nil {
			return err
		}
		if _, err := cw.Write(b); err != nil {
			return err
		}
	}

	// t.OldVirtPrice (big.Int) (struct)
	{
		if t.OldVirtPrice != nil && t.OldVirtPrice.Sign() < 0 {
			return xerrors.Errorf("Value in field t.OldVirtPrice was a negative big-integer (not supported)")
		}
		if err := cw.CborWriteHeader(cbg.MajTag, 2); err != nil {
			return err
		}
		var b []byte
		if t.OldVirtPrice != nil {
			b = t.OldVirtPrice.Bytes()
		}

		if err := cw.CborWriteHeader(cbg.MajByteString, uint64(len(b))); err != nil {
			return err
		}
		if _, err := cw.Write(b); err != nil {
			return err
		}
	}

	// t.NewVirtPrice (big.Int) (struct)
	{
		if t.NewVirtPrice != nil && t.NewVirtPrice.Sign() < 0 {
			return xerrors.Errorf("Value in field t.NewVirtPrice was a negative big-integer (not supported)")
		}
		if err := cw.CborWriteHeader(cbg.MajTag, 2); err != nil {
			return err
		}
		var b []byte
		if t.NewVirtPrice != nil {
			b = t.NewVirtPrice.Bytes()
		}

		if err := cw.CborWriteHeader(cbg.MajByteString, uint64(len(b))); err != nil {
			return err
		}
		if _, err := cw.Write(b); err != nil {
			return err
		}
	}

	// t.Epoch (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Epoch)); err != nil {
		return err
	}

	// t.PriceEMA (big.Int) (struct)
	{
		if t.PriceEMA != nil && t.PriceEMA.Sign() < 0 {
			return xerrors.Errorf("Value in field t.PriceEMA was a negative big-integer (not supported)")
		}
		if err := cw.CborWriteHeader(cbg.MajTag, 2); err != nil {
			return err
		}
		var b []byte
		if t.PriceEMA != nil {
			b = t.PriceEMA.Bytes()
		}

		if err := cw.CborWriteHeader(cbg.MajByteString, uint64(len(b))); err != nil {
			return err
		}
		if _, err := cw.Write(b); err != nil {
			return err
		}
	}
	return nil
}

func (t *RepegOp) UnmarshalCBOR(r io.Reader) (err error) {
	*t = RepegOp{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 7 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.PoolID (string) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.PoolID = string(sval)
	}
	// t.OldPriceScale (big.Int) (struct)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if maj != cbg.MajTag || extra != 2 {
		return fmt.Errorf("big ints should be cbor bignums")
	}

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if maj != cbg.MajByteString {
		return fmt.Errorf("big ints should be tagged cbor byte strings")
	}

	if extra > 256 {
		return fmt.Errorf("t.OldPriceScale: cbor bignum was too large")
	}

	if extra > 0 {
		buf := make([]byte, extra)
		if _, err := io.ReadFull(cr, buf); err != nil {
			return err
		}
		t.OldPriceScale = big.NewInt(0).SetBytes(buf)
	} else {
		t.OldPriceScale = big.NewInt(0)
	}
	// t.NewPriceScale (big.Int) (struct)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if maj != cbg.MajTag || extra != 2 {
		return fmt.Errorf("big ints should be cbor bignums")
	}

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if maj != cbg.MajByteString {
		return fmt.Errorf("big ints should be tagged cbor byte strings")
	}

	if extra > 256 {
		return fmt.Errorf("t.NewPriceScale: cbor bignum was too large")
	}

	if extra > 0 {
		buf := make([]byte, extra)
		if _, err := io.ReadFull(cr, buf); err != nil {
			return err
		}
		t.NewPriceScale = big.NewInt(0).SetBytes(buf)
	} else {
		t.NewPriceScale = big.NewInt(0)
	}
	// t.OldVirtPrice (big.Int) (struct)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if maj != cbg.MajTag || extra != 2 {
		return fmt.Errorf("big ints should be cbor bignums")
	}

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if maj != cbg.MajByteString {
		return fmt.Errorf("big ints should be tagged cbor byte strings")
	}

	if extra > 256 {
		return fmt.Errorf("t.OldVirtPrice: cbor bignum was too large")
	}

	if extra > 0 {
		buf := make([]byte, extra)
		if _, err := io.ReadFull(cr, buf); err != nil {
			return err
		}
		t.OldVirtPrice = big.NewInt(0).SetBytes(buf)
	} else {
		t.OldVirtPrice = big.NewInt(0)
	}
	// t.NewVirtPrice (big.Int) (struct)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if maj != cbg.MajTag || extra != 2 {
		return fmt.Errorf("big ints should be cbor bignums")
	}

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if maj != cbg.MajByteString {
		return fmt.Errorf("big ints should be tagged cbor byte strings")
	}

	if extra > 256 {
		return fmt.Errorf("t.NewVirtPrice: cbor bignum was too large")
	}

	if extra > 0 {
		buf := make([]byte, extra)
		if _, err := io.ReadFull(cr, buf); err != nil {
			return err
		}
		t.NewVirtPrice = big.NewInt(0).SetBytes(buf)
	} else {
		t.NewVirtPrice = big.NewInt(0)
	}
	// t.Epoch (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Epoch = uint64(extra)

	}
	// t.PriceEMA (big.Int) (struct)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if maj != cbg.MajTag || extra != 2 {
		return fmt.Errorf("big ints should be cbor bignums")
	}

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if maj != cbg.MajByteString {
		return fmt.Errorf("big ints should be tagged cbor byte strings")
	}

	if extra > 256 {
		return fmt.Errorf("t.PriceEMA: cbor bignum was too large")
	}

	if extra > 0 {
		buf := make([]byte, extra)
		if _, err := io.ReadFull(cr, buf); err != nil {
			return err
		}
		t.PriceEMA = big.NewInt(0).SetBytes(buf)
	} else {
		t.PriceEMA = big.NewInt(0)
	}
	return nil
}

var lengthBufSessionCloseOp = []byte{133}

func (t *SessionCloseOp) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufSessionCloseOp); err != nil {
		return err
	}

	// t.SessionID ([32]uint8) (array)
	if len(t.SessionID) > 2097152 {
		return xerrors.Errorf("Byte array in field t.SessionID was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.SessionID))); err != nil {
		return err
	}

	if _, err := cw.Write(t.SessionID[:]); err != nil {
		return err
	}

	// t.Version (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Version)); err != nil {
		return err
	}

	// t.UserAmount (decimal.Decimal) (struct)
	if err := t.UserAmount.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.ServiceAmount (decimal.Decimal) (struct)
	if err := t.ServiceAmount.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Cooperative (bool) (bool)
	if err := cbg.WriteBool(w, t.Cooperative); err != nil {
		return err
	}
	return nil
}

func (t *SessionCloseOp) UnmarshalCBOR(r io.Reader) (err error) {
	*t = SessionCloseOp{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 5 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.SessionID ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.SessionID: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.SessionID = [32]uint8{}
	if _, err := io.ReadFull(cr, t.SessionID[:]); err != nil {
		return err
	}
	// t.Version (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Version = uint64(extra)

	}
	// t.UserAmount (decimal.Decimal) (struct)

	{

		if err := t.UserAmount.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.UserAmount: %w", err)
		}

	}
	// t.ServiceAmount (decimal.Decimal) (struct)

	{

		if err := t.ServiceAmount.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.ServiceAmount: %w", err)
		}

	}
	// t.Cooperative (bool) (bool)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}
	if maj != cbg.MajOther {
		return fmt.Errorf("booleans must be major type 7")
	}
	switch extra {
	case 20:
		t.Cooperative = false
	case 21:
		t.Cooperative = true
	default:
		return fmt.Errorf("booleans are either major type 7, value 20 or 21 (got %d)", extra)
	}
	return nil
}

var lengthBufSessionChallengeOp = []byte{132}

func (t *SessionChallengeOp) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufSessionChallengeOp); err != nil {
		return err
	}

	// t.SessionID ([32]uint8) (array)
	if len(t.SessionID) > 2097152 {
		return xerrors.Errorf("Byte array in field t.SessionID was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.SessionID))); err != nil {
		return err
	}

	if _, err := cw.Write(t.SessionID[:]); err != nil {
		return err
	}

	// t.PreviousVersion (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.PreviousVersion)); err != nil {
		return err
	}

	// t.NewVersion (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.NewVersion)); err != nil {
		return err
	}

	// t.NewDeadline (int64) (int64)
	if t.NewDeadline >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.NewDeadline)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.NewDeadline-1)); err != nil {
			return err
		}
	}

	return nil
}

func (t *SessionChallengeOp) UnmarshalCBOR(r io.Reader) (err error) {
	*t = SessionChallengeOp{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 4 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.SessionID ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.SessionID: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.SessionID = [32]uint8{}
	if _, err := io.ReadFull(cr, t.SessionID[:]); err != nil {
		return err
	}
	// t.PreviousVersion (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.PreviousVersion = uint64(extra)

	}
	// t.NewVersion (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.NewVersion = uint64(extra)

	}
	// t.NewDeadline (int64) (int64)
	{
		maj, extra, err := cr.ReadHeader()
		if err != nil {
			return err
		}
		var extraI int64
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative overflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.NewDeadline = int64(extraI)
	}
	return nil
}

var lengthBufBlockEntryRef = []byte{130}

func (t *BlockEntryRef) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufBlockEntryRef); err != nil {
		return err
	}

	// t.BlockHash ([32]uint8) (array)
	if len(t.BlockHash) > 2097152 {
		return xerrors.Errorf("Byte array in field t.BlockHash was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.BlockHash))); err != nil {
		return err
	}

	if _, err := cw.Write(t.BlockHash[:]); err != nil {
		return err
	}

	// t.EntryIndex (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.EntryIndex)); err != nil {
		return err
	}

	return nil
}

func (t *BlockEntryRef) UnmarshalCBOR(r io.Reader) (err error) {
	*t = BlockEntryRef{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.BlockHash ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.BlockHash: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.BlockHash = [32]uint8{}
	if _, err := io.ReadFull(cr, t.BlockHash[:]); err != nil {
		return err
	}
	// t.EntryIndex (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.EntryIndex = uint64(extra)

	}
	return nil
}

var lengthBufBurnReceipt = []byte{133}

func (t *BurnReceipt) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufBurnReceipt); err != nil {
		return err
	}

	// t.WithdrawalID ([32]uint8) (array)
	if len(t.WithdrawalID) > 2097152 {
		return xerrors.Errorf("Byte array in field t.WithdrawalID was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.WithdrawalID))); err != nil {
		return err
	}

	if _, err := cw.Write(t.WithdrawalID[:]); err != nil {
		return err
	}

	// t.BlockEntryRef (core.BlockEntryRef) (struct)
	if err := t.BlockEntryRef.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.L1TxHash ([32]uint8) (array)
	if len(t.L1TxHash) > 2097152 {
		return xerrors.Errorf("Byte array in field t.L1TxHash was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.L1TxHash))); err != nil {
		return err
	}

	if _, err := cw.Write(t.L1TxHash[:]); err != nil {
		return err
	}

	// t.Signatures ([][]uint8) (slice)
	if len(t.Signatures) > 8192 {
		return xerrors.Errorf("Slice value in field t.Signatures was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Signatures))); err != nil {
		return err
	}
	for _, v := range t.Signatures {
		if len(v) > 2097152 {
			return xerrors.Errorf("Byte array in field v was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(v))); err != nil {
			return err
		}

		if _, err := cw.Write(v); err != nil {
			return err
		}

	}

	// t.Status (core.WithdrawalOutcome) (uint8)
	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Status)); err != nil {
		return err
	}
	return nil
}

func (t *BurnReceipt) UnmarshalCBOR(r io.Reader) (err error) {
	*t = BurnReceipt{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 5 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.WithdrawalID ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.WithdrawalID: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.WithdrawalID = [32]uint8{}
	if _, err := io.ReadFull(cr, t.WithdrawalID[:]); err != nil {
		return err
	}
	// t.BlockEntryRef (core.BlockEntryRef) (struct)

	{

		if err := t.BlockEntryRef.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.BlockEntryRef: %w", err)
		}

	}
	// t.L1TxHash ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.L1TxHash: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.L1TxHash = [32]uint8{}
	if _, err := io.ReadFull(cr, t.L1TxHash[:]); err != nil {
		return err
	}
	// t.Signatures ([][]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 8192 {
		return fmt.Errorf("t.Signatures: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Signatures = make([][]uint8, extra)
	}

	for i := 0; i < int(extra); i++ {
		{
			var maj byte
			var extra uint64
			var err error
			_ = maj
			_ = extra
			_ = err

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.Signatures[i]: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.Signatures[i] = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.Signatures[i]); err != nil {
				return err
			}

		}
	}
	// t.Status (core.WithdrawalOutcome) (uint8)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}
	if maj != cbg.MajUnsignedInt {
		return fmt.Errorf("wrong type for uint8 field")
	}
	if extra > math.MaxUint8 {
		return fmt.Errorf("integer in input was too large for uint8 field")
	}
	t.Status = WithdrawalOutcome(extra)
	return nil
}

var lengthBufMintReceipt = []byte{136}

func (t *MintReceipt) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufMintReceipt); err != nil {
		return err
	}

	// t.ChainID (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.ChainID)); err != nil {
		return err
	}

	// t.L1TxHash ([32]uint8) (array)
	if len(t.L1TxHash) > 2097152 {
		return xerrors.Errorf("Byte array in field t.L1TxHash was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.L1TxHash))); err != nil {
		return err
	}

	if _, err := cw.Write(t.L1TxHash[:]); err != nil {
		return err
	}

	// t.LogIndex (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.LogIndex)); err != nil {
		return err
	}

	// t.Account (string) (string)
	if len(t.Account) > 8192 {
		return xerrors.Errorf("Value in field t.Account was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Account))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Account)); err != nil {
		return err
	}

	// t.Asset (string) (string)
	if len(t.Asset) > 8192 {
		return xerrors.Errorf("Value in field t.Asset was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Asset))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Asset)); err != nil {
		return err
	}

	// t.Amount (big.Int) (struct)
	{
		if t.Amount != nil && t.Amount.Sign() < 0 {
			return xerrors.Errorf("Value in field t.Amount was a negative big-integer (not supported)")
		}
		if err := cw.CborWriteHeader(cbg.MajTag, 2); err != nil {
			return err
		}
		var b []byte
		if t.Amount != nil {
			b = t.Amount.Bytes()
		}

		if err := cw.CborWriteHeader(cbg.MajByteString, uint64(len(b))); err != nil {
			return err
		}
		if _, err := cw.Write(b); err != nil {
			return err
		}
	}

	// t.BlockNumber (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.BlockNumber)); err != nil {
		return err
	}

	// t.Signatures ([][]uint8) (slice)
	if len(t.Signatures) > 8192 {
		return xerrors.Errorf("Slice value in field t.Signatures was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Signatures))); err != nil {
		return err
	}
	for _, v := range t.Signatures {
		if len(v) > 2097152 {
			return xerrors.Errorf("Byte array in field v was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(v))); err != nil {
			return err
		}

		if _, err := cw.Write(v); err != nil {
			return err
		}

	}
	return nil
}

func (t *MintReceipt) UnmarshalCBOR(r io.Reader) (err error) {
	*t = MintReceipt{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 8 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.ChainID (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.ChainID = uint64(extra)

	}
	// t.L1TxHash ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.L1TxHash: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.L1TxHash = [32]uint8{}
	if _, err := io.ReadFull(cr, t.L1TxHash[:]); err != nil {
		return err
	}
	// t.LogIndex (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.LogIndex = uint64(extra)

	}
	// t.Account (string) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.Account = string(sval)
	}
	// t.Asset (string) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.Asset = string(sval)
	}
	// t.Amount (big.Int) (struct)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if maj != cbg.MajTag || extra != 2 {
		return fmt.Errorf("big ints should be cbor bignums")
	}

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if maj != cbg.MajByteString {
		return fmt.Errorf("big ints should be tagged cbor byte strings")
	}

	if extra > 256 {
		return fmt.Errorf("t.Amount: cbor bignum was too large")
	}

	if extra > 0 {
		buf := make([]byte, extra)
		if _, err := io.ReadFull(cr, buf); err != nil {
			return err
		}
		t.Amount = big.NewInt(0).SetBytes(buf)
	} else {
		t.Amount = big.NewInt(0)
	}
	// t.BlockNumber (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.BlockNumber = uint64(extra)

	}
	// t.Signatures ([][]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 8192 {
		return fmt.Errorf("t.Signatures: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Signatures = make([][]uint8, extra)
	}

	for i := 0; i < int(extra); i++ {
		{
			var maj byte
			var extra uint64
			var err error
			_ = maj
			_ = extra
			_ = err

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.Signatures[i]: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.Signatures[i] = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.Signatures[i]); err != nil {
				return err
			}

		}
	}
	return nil
}

var lengthBufFinalizedWithdrawal = []byte{134}

func (t *FinalizedWithdrawal) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufFinalizedWithdrawal); err != nil {
		return err
	}

	// t.WithdrawalID ([32]uint8) (array)
	if len(t.WithdrawalID) > 2097152 {
		return xerrors.Errorf("Byte array in field t.WithdrawalID was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.WithdrawalID))); err != nil {
		return err
	}

	if _, err := cw.Write(t.WithdrawalID[:]); err != nil {
		return err
	}

	// t.BlockHash ([32]uint8) (array)
	if len(t.BlockHash) > 2097152 {
		return xerrors.Errorf("Byte array in field t.BlockHash was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.BlockHash))); err != nil {
		return err
	}

	if _, err := cw.Write(t.BlockHash[:]); err != nil {
		return err
	}

	// t.EntryIndex (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.EntryIndex)); err != nil {
		return err
	}

	// t.FinalizedAt (int64) (int64)
	if t.FinalizedAt >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.FinalizedAt)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.FinalizedAt-1)); err != nil {
			return err
		}
	}

	// t.Attestation (core.Attestation) (struct)
	if err := t.Attestation.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Block (core.Block) (struct)
	if err := t.Block.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *FinalizedWithdrawal) UnmarshalCBOR(r io.Reader) (err error) {
	*t = FinalizedWithdrawal{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 6 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.WithdrawalID ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.WithdrawalID: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.WithdrawalID = [32]uint8{}
	if _, err := io.ReadFull(cr, t.WithdrawalID[:]); err != nil {
		return err
	}
	// t.BlockHash ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.BlockHash: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.BlockHash = [32]uint8{}
	if _, err := io.ReadFull(cr, t.BlockHash[:]); err != nil {
		return err
	}
	// t.EntryIndex (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.EntryIndex = uint64(extra)

	}
	// t.FinalizedAt (int64) (int64)
	{
		maj, extra, err := cr.ReadHeader()
		if err != nil {
			return err
		}
		var extraI int64
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative overflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.FinalizedAt = int64(extraI)
	}
	// t.Attestation (core.Attestation) (struct)

	{

		if err := t.Attestation.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.Attestation: %w", err)
		}

	}
	// t.Block (core.Block) (struct)

	{

		if err := t.Block.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.Block: %w", err)
		}

	}
	return nil
}

var lengthBufFinalizedWithdrawalHeader = []byte{132}

func (t *FinalizedWithdrawalHeader) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufFinalizedWithdrawalHeader); err != nil {
		return err
	}

	// t.WithdrawalID ([32]uint8) (array)
	if len(t.WithdrawalID) > 2097152 {
		return xerrors.Errorf("Byte array in field t.WithdrawalID was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.WithdrawalID))); err != nil {
		return err
	}

	if _, err := cw.Write(t.WithdrawalID[:]); err != nil {
		return err
	}

	// t.BlockHash ([32]uint8) (array)
	if len(t.BlockHash) > 2097152 {
		return xerrors.Errorf("Byte array in field t.BlockHash was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.BlockHash))); err != nil {
		return err
	}

	if _, err := cw.Write(t.BlockHash[:]); err != nil {
		return err
	}

	// t.EntryIndex (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.EntryIndex)); err != nil {
		return err
	}

	// t.FinalizedAt (int64) (int64)
	if t.FinalizedAt >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.FinalizedAt)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.FinalizedAt-1)); err != nil {
			return err
		}
	}

	return nil
}

func (t *FinalizedWithdrawalHeader) UnmarshalCBOR(r io.Reader) (err error) {
	*t = FinalizedWithdrawalHeader{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 4 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.WithdrawalID ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.WithdrawalID: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.WithdrawalID = [32]uint8{}
	if _, err := io.ReadFull(cr, t.WithdrawalID[:]); err != nil {
		return err
	}
	// t.BlockHash ([32]uint8) (array)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.BlockHash: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}
	if extra != 32 {
		return fmt.Errorf("expected array to have 32 elements")
	}

	t.BlockHash = [32]uint8{}
	if _, err := io.ReadFull(cr, t.BlockHash[:]); err != nil {
		return err
	}
	// t.EntryIndex (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.EntryIndex = uint64(extra)

	}
	// t.FinalizedAt (int64) (int64)
	{
		maj, extra, err := cr.ReadHeader()
		if err != nil {
			return err
		}
		var extraI int64
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return fmt.Errorf("int64 negative overflow")
			}
			extraI = -1 - extraI
		default:
			return fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.FinalizedAt = int64(extraI)
	}
	return nil
}
