name: Push on master

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  unit:
    name: Unit
    uses: ./.github/workflows/test-go.yml

  typescript:
    name: TypeScript
    uses: ./.github/workflows/test-ts.yml

  integration:
    name: Integration
    uses: ./.github/workflows/test-integration.yml
