name: PR on master

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  unit:
    name: Unit
    uses: ./.github/workflows/test-go.yml

  integration:
    name: Integration
    uses: ./.github/workflows/test-integration.yml
